/**
 * FileService2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BinaryData } from './binaryData';
import { HttpHeader } from './httpHeader';
import { Stream } from './stream';

export interface Response { 
    readonly status?: number;
    readonly reasonPhrase?: string;
    contentStream?: Stream;
    clientRequestId?: string;
    readonly headers?: Array<HttpHeader>;
    content?: BinaryData;
    readonly isError?: boolean;
}