export * from './account.service';
import { AccountService } from './account.service';
export * from './chat.service';
import { ChatService } from './chat.service';
export * from './message.service';
import { MessageService } from './message.service';
export * from './remind.service';
import { RemindService } from './remind.service';
export * from './signalR.service';
import { SignalRService } from './signalR.service';
export * from './vk.service';
import { VkService } from './vk.service';
export const APIS = [AccountService, ChatService, MessageService, RemindService, SignalRService, VkService];
